VERSION 0.7
PROJECT sjerred/better-skill-capped

deps:
  FROM ../+node
  COPY package*.json .
  RUN npm ci
  SAVE ARTIFACT package*.json AS LOCAL ./

src:
  FROM +deps
  COPY --dir src tsconfig.json wrangler.toml .

build:
  FROM +src
  RUN npm run build

deploy:
  FROM +src
  RUN --push --secret CLOUDFLARE_API_TOKEN=cloudflare_api_token npm run deploy
